#!/bin/bash
# This script generates the ContentBlockerConverterVersion.swift file with
# library and component versions, and sets the same version in package.json.
#
# The version is the most recent released one in CHANGELOG.md, which is the
# single source of truth: the release tag is derived from it as well.
#
# Usage: ./scripts/make/codegen.sh

set -e

ROOT="$(dirname "$0")/../.."
CHANGELOG="$ROOT/CHANGELOG.md"
PACKAGE_JSON="$ROOT/Extension/package.json"
OUTPUT_DIR="$ROOT/Sources/ContentBlockerConverter"
OUTPUT_FILE="$OUTPUT_DIR/ContentBlockerConverterVersion.swift"

if [ ! -f "$CHANGELOG" ]; then
    echo "CHANGELOG.md not found at $CHANGELOG"
    exit 1
fi

if [ ! -f "$PACKAGE_JSON" ]; then
    echo "package.json not found at $PACKAGE_JSON"
    exit 1
fi

# The first numbered heading, skipping "## [Unreleased]". Keep the pattern in
# sync with the CI version check and with actions/update-changelog.
LIB_VERSION="$(
    grep -m1 -oE '^## \[[0-9]+\.[0-9]+\.[0-9]+[^]]*\]' "$CHANGELOG" |
        sed 's/^## \[//; s/\]$//'
)"

if [ -z "$LIB_VERSION" ]; then
    echo "No released version found in CHANGELOG.md."
    echo "Expected a heading like \"## [1.2.3] - 2026-01-01\"."
    exit 1
fi

echo "Version from CHANGELOG.md: $LIB_VERSION"

# Set the version field in package.json to LIB_VERSION
TMP_PKG_JSON="$PACKAGE_JSON.tmp"
jq --arg ver "$LIB_VERSION" '.version = $ver' "$PACKAGE_JSON" >"$TMP_PKG_JSON" && mv "$TMP_PKG_JSON" "$PACKAGE_JSON"

echo "Set version in $PACKAGE_JSON to $LIB_VERSION"

# Extract versions using jq
SCRIPTLETS_VERSION=$(jq -r '.dependencies["@adguard/scriptlets"]' "$PACKAGE_JSON" | sed 's/^\^//')
EXTENDEDCSS_VERSION=$(jq -r '.dependencies["@adguard/extended-css"]' "$PACKAGE_JSON" | sed 's/^\^//')

if [ -z "$SCRIPTLETS_VERSION" ] || [ "$SCRIPTLETS_VERSION" == "null" ]; then
    echo "@adguard/scriptlets version not found in package.json"
    exit 1
fi
if [ -z "$EXTENDEDCSS_VERSION" ] || [ "$EXTENDEDCSS_VERSION" == "null" ]; then
    echo "@adguard/extended-css version not found in package.json"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

cat <<SWIFT >"$OUTPUT_FILE"
// This file is auto-generated by scripts/make/codegen.sh. Do not edit manually!

/// Version information for the SafariConverterLib and its components. It can be
/// used in the apps that are using this library.
public enum ContentBlockerConverterVersion {
    /// Version of SafariConverterLib and @adguard/safari-extension.
    public static let library = "$LIB_VERSION"

    /// Version of @adguard/scriptlets (component of the JS library).
    public static let scriptlets = "$SCRIPTLETS_VERSION"

    /// Version of @adguard/extended-css (component of the JS library).
    public static let extendedCSS = "$EXTENDEDCSS_VERSION"
}
SWIFT

echo "Generated $OUTPUT_FILE"
