import Foundation
import PackagePlugin

/// Generates `ContentBlockerConverterVersion` at build time.
///
/// The version is never stored in the repository: CHANGELOG.md is the only
/// place it is written, and this plugin reads the most recent released section
/// from it. Component versions come from Extension/package.json, which is the
/// source of truth for the JS dependencies.
///
/// Running as a build tool plugin means consumers get the constant too — they
/// compile the package from source, and the plugin runs as part of that build.
@main
struct GenerateVersion: BuildToolPlugin {
    func createBuildCommands(context: PluginContext, target: Target) throws -> [Command] {
        let changelog = context.package.directory.appending("CHANGELOG.md")
        let packageJSON = context.package.directory.appending(["Extension", "package.json"])
        let output = context.pluginWorkDirectory.appending("ContentBlockerConverterVersion.swift")

        let library = try libraryVersion(changelogPath: changelog.string)
        let components = try componentVersions(packageJSONPath: packageJSON.string)

        let source = """
            // This file is generated by the GenerateVersion build plugin. Do not edit,
            // and do not commit it: the version lives in CHANGELOG.md only.

            /// Version information for the SafariConverterLib and its components. It can be
            /// used in the apps that are using this library.
            public enum ContentBlockerConverterVersion {
                /// Version of SafariConverterLib and @adguard/safari-extension.
                public static let library = "\(library)"

                /// Version of @adguard/scriptlets (component of the JS library).
                public static let scriptlets = "\(components.scriptlets)"

                /// Version of @adguard/extended-css (component of the JS library).
                public static let extendedCSS = "\(components.extendedCSS)"
            }

            """

        try source.write(toFile: output.string, atomically: true, encoding: .utf8)

        // The file is already written above; the command exists so that SwiftPM
        // registers the output as a source file and re-runs the plugin whenever
        // one of the inputs changes.
        return [
            .buildCommand(
                displayName: "Generate ContentBlockerConverterVersion.swift (\(library))",
                executable: Path("/usr/bin/true"),
                arguments: [],
                inputFiles: [changelog, packageJSON],
                outputFiles: [output]
            )
        ]
    }

    /// The first numbered heading in the changelog, e.g. `## [4.3.0] - 2026-06-04`.
    /// Keep the shape in sync with actions/parse-changelog and update-changelog.
    private func libraryVersion(changelogPath: String) throws -> String {
        let text = try String(contentsOfFile: changelogPath, encoding: .utf8)

        for line in text.split(separator: "\n", omittingEmptySubsequences: false)
        where line.hasPrefix("## [") {
            guard let open = line.firstIndex(of: "["),
                let close = line.firstIndex(of: "]")
            else { continue }

            let version = String(line[line.index(after: open)..<close])
            if version.first?.isNumber == true {
                return version
            }
        }

        throw PluginError.noReleasedVersion(changelogPath)
    }

    private func componentVersions(
        packageJSONPath: String
    ) throws -> (scriptlets: String, extendedCSS: String) {
        let data = try Data(contentsOf: URL(fileURLWithPath: packageJSONPath))
        guard
            let root = try JSONSerialization.jsonObject(with: data) as? [String: Any],
            let dependencies = root["dependencies"] as? [String: String]
        else {
            throw PluginError.malformedPackageJSON(packageJSONPath)
        }

        func requirement(_ name: String) throws -> String {
            guard let raw = dependencies[name] else {
                throw PluginError.missingDependency(name)
            }
            // Strip a leading range operator, e.g. "^2.3.1" -> "2.3.1".
            return raw.trimmingCharacters(in: CharacterSet(charactersIn: "^~>=< "))
        }

        return (try requirement("@adguard/scriptlets"), try requirement("@adguard/extended-css"))
    }
}

private enum PluginError: Error, CustomStringConvertible {
    case noReleasedVersion(String)
    case malformedPackageJSON(String)
    case missingDependency(String)

    var description: String {
        switch self {
        case .noReleasedVersion(let path):
            return "No released version found in \(path); expected a heading like \"## [1.2.3]\""
        case .malformedPackageJSON(let path):
            return "Could not read dependencies from \(path)"
        case .missingDependency(let name):
            return "Dependency \(name) not found in package.json"
        }
    }
}
