// This file is auto-generated by scripts/make/codegen.sh. Do not edit manually!

/// Version information for the SafariConverterLib and its components. It can be
/// used in the apps that are using this library.
public enum ContentBlockerConverterVersion {
    /// Version of SafariConverterLib and @adguard/safari-extension.
    public static let library = "3.0.0"

    /// Version of @adguard/scriptlets (component of the JS library).
    public static let scriptlets = "2.1.4"

    /// Version of @adguard/extended-css (component of the JS library).
    public static let extendedCSS = "2.1.1"
}
