---
version: 2
plan:
  project-key: IOS
  key: CIVSPECS
  name: Converter - increment version
variables:
  dockerNode: node:18.14.0-buster-slim
stages:
  - Increment:
      manual: false
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            yarn run increment
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skip ci: Automatic increment version'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete:
    after-deleted-days: 7
    after-inactive-days: 14
  integration:
    push-on-success: false
    merge-from: Converter - increment version
  link-to-jira: true

notifications:
  - events:
      - plan-failed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
